SET search_path TO "DBPERSON";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "TB_PERSON"
(
    "ID_PERSON"       BIGSERIAL,
    "UUID"              VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "FULL_NAME"       VARCHAR(60) NOT NULL,
    "NM_FATHER"       VARCHAR(60),
    "NM_MOTHER"       VARCHAR(60) NOT NULL,
    "DOCUMENT_NUMBER" VARCHAR(15) NOT NULL UNIQUE,
    "DT_BIRTH"        DATE        NOT NULL,
    "DT_INCLUSION"    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TP_SEX"          VARCHAR(1)  NOT NULL,
    "EMAIL"           VARCHAR(70) NOT NULL UNIQUE,
    PRIMARY KEY ("ID_PERSON")
);