SET search_path TO "DBPERSON";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table IF NOT EXISTS "TB_WEIGHT_HEIGHT"
      (
          "ID_WEIGHT_HEIGHT"     BIGSERIAL,
          "ID_PERSON"    BIGSERIAL,
          "UUID"       VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
          "WEIGHT"      VARCHAR(12) NOT NULL,
          "HEIGHT"      VARCHAR(12) NOT NULL,
          "DT_INCLUSION" TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
       FOREIGN KEY ("ID_PERSON") REFERENCES "TB_PERSON" ("ID_PERSON"),
       PRIMARY KEY ("ID_WEIGHT_HEIGHT")
      );